server:
  port: 8082
  application:
    name: demo
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasources:
    tenant1:
      url: jdbc:mysql://localhost:3306/tenant1
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    tenant2:
      url: jdbc:mysql://localhost:3306/tenant2
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 652c85cd3d1953
    password: 5a50d79d740bf4
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

otel:
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://localhost:4317  # Endpoint do OpenTelemetry Collector para gRPC
      protocol: grpc
  service:
    name: demo
  logging:
    level:
      org.springframework.cloud.sleuth: DEBUG
      io.opentelemetry: DEBUG