server:
  port: 8082

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasources:
    tenant1:
      url: jdbc:mysql://localhost:3306/tenant1
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    tenant2:
      url: jdbc:mysql://localhost:3306/tenant2
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
